# Generated by Django 2.0.1 on 2018-01-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('kind', models.CharField(max_length=200, verbose_name='种类')),
                ('goods_id', models.CharField(max_length=100, verbose_name='编号')),
                ('image', models.ImageField(upload_to='goods', verbose_name='图片')),
                ('summary', models.TextField(verbose_name='摘要')),
                ('get_in', models.IntegerField(default=0, verbose_name='收入数量')),
                ('get_out', models.IntegerField(default=0, verbose_name='支出数量')),
                ('get_left', models.IntegerField(default=0, verbose_name='结余数量')),
                ('state', models.IntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['-time'],
            },
        ),
    ]
